TIMES = [
    'Sunday morning',
    'Sunday noon',
    'Sunday afternoon',
    'Sunday evening',
    'Monday morning',
    'Monday noon',
    'Monday afternoon',
    'Monday evening',
    'Tuesday morning',
    'Tuesday noon',
    'Tuesday afternoon',
    'Tuesday evening',
    'Wednesday morning',
    'Wednesday noon',
    'Wednesday afternoon',
    'Wednesday evening',
    'Thursday morning',
    'Thursday noon',
    'Thursday afternoon',
    'Thursday evening',
    'Friday morning',
    'Friday noon',
    'Friday afternoon',
    'Friday evening',
    'Saturday morning',
    'Saturday noon',
    'Saturday afternoon',
    'Saturday evening',
]

PLACES =  [
    'Golan Heights',
    'Ramon Crater',
    'Dead Sea',
    'Eilat',
    'Gym',
    "Mike's Place",
    'The Neighbours Supermarket',
    'Work',
    'Shalvata Club',
    'The western wall',
    'The Gordon Beach',
    'The Eiffel Tower',
    'Ramla',
    'Bloomfield Stadium',
    'Menora Mivtachim Arena',
    'The Minzar BAR in Tel Aviv',
    'Azrieli Mall',
    'The Yarkon Park',
    'The Jordan River'
]
